# Generated by Django 4.0.6 on 2022-12-08 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10000000)),
                ('amount', models.CharField(max_length=10000000)),
                ('withdrawal_id', models.CharField(max_length=10000000)),
                ('OriginatorConversationID', models.TextField()),
                ('ResponseCode', models.TextField()),
                ('ResponseDescription', models.TextField()),
                ('ResultType', models.TextField()),
                ('ResultCode', models.TextField()),
                ('ResultDesc', models.TextField()),
                ('OriginatorConversationID2', models.TextField()),
                ('ConversationID2', models.TextField()),
                ('ConversationID', models.TextField()),
                ('TransactionAmount', models.TextField()),
                ('TransactionReceipt', models.TextField()),
                ('TransactionID', models.TextField()),
                ('B2CRecipientIsRegisteredCustomer', models.TextField()),
                ('B2CChargesPaidAccountAvailableFunds', models.TextField()),
                ('ReceiverPartyPublicName', models.TextField()),
                ('B2CUtilityAccountAvailableFunds', models.TextField()),
                ('B2CWorkingAccountAvailableFunds', models.TextField()),
                ('TransactionCompletedDateTime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_title', models.CharField(max_length=10000000)),
                ('Withdrawal_code', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='EventTotals2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipts2', models.TextField()),
                ('proceeding', models.TextField()),
                ('owner', models.TextField()),
                ('checkoutRequestID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExistingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('type', models.TextField()),
                ('reference', models.TextField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.TextField()),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='MpesaPaymentCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_title', models.TextField()),
                ('Event_price', models.TextField()),
                ('Withdrawal_code', models.TextField()),
                ('BusinessShortCode', models.TextField()),
                ('Timestamp', models.TextField()),
                ('TransactionType', models.TextField()),
                ('Amount', models.TextField()),
                ('PartyA', models.TextField()),
                ('PartyB', models.TextField()),
                ('PhoneNumber', models.TextField()),
                ('AccountReference', models.TextField()),
                ('MerchantRequestID', models.TextField()),
                ('CheckoutRequestID', models.TextField()),
                ('TransactionStatus1', models.IntegerField()),
                ('TransactionDescription1', models.TextField()),
                ('CustomerMessage', models.TextField()),
                ('TransactionStatus2', models.TextField()),
                ('TransactionDescription2', models.TextField()),
                ('ItemAmountPaid', models.TextField()),
                ('ItemReceipt', models.TextField()),
                ('PhoneNumber2', models.TextField()),
                ('ItemDate', models.TextField()),
                ('CompanyAmount', models.TextField()),
                ('OrganisersAmount', models.TextField()),
                ('mpesa_receipt', models.CharField(max_length=10000000)),
                ('ticket_no', models.IntegerField(null=True)),
                ('ticket_title', models.CharField(max_length=10000000)),
                ('phone_number', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='OrganiserCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('made_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_organiser', models.CharField(max_length=100)),
                ('ticket_title', models.CharField(max_length=100)),
                ('ticket_price', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('event_start_time', models.CharField(max_length=100)),
                ('event_end_time', models.CharField(max_length=100)),
                ('first_act_time', models.CharField(max_length=100)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesareceipt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('price', models.PositiveIntegerField(default=0)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
